services:
  bot:
    build:
      context: .
    env_file: .env
    environment:
      NODE_ENV: production
    volumes:
      - cytube-data:/usr/src/app/data
    restart: unless-stopped

volumes:
  cytube-data:
